# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    omx_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    omx_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    omx_gripper_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

omx_joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

omx_gripper_joint_trajectory_controller:
  ros__parameters:
    joints:
      - gripper_left_joint
      - gripper_right_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
